language: en-US
tone_instructions: ""
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions: [ ]
  path_filters: [ ]
  path_instructions:
    - path: "**/*.*"
      instructions: |
        Be extremely rigorous in code reviews.
        Enforce strict adherence to .NET best practices and design patterns (e.g., SOLID, Clean Architecture).
        Ensure code readability with clear, descriptive, and consistent naming conventions that reflect each element’s purpose (following .NET naming guidelines).
        Require explicit typing; avoid using dynamic or object unnecessarily.
        Disallow unnecessarily nested methods or local functions that reduce clarity.
        Promote modularity and proper separation of concerns across layers and services.
        Limit the number of method parameters; refactor to reduce complexity when appropriate (e.g., use DTOs or parameter objects).
        Prohibit the use of Console.WriteLine or debugging output in production code; use proper logging mechanisms like ILogger.
        Avoid vague or generic variable names like temp, data, item, test, or value; use meaningful names that clearly indicate intent and context..
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [ ]
    labels: [ ]
    drafts: true
    base_branches: [ ]
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: picky
      enabled_rules: [ ]
      disabled_rules: [ ]
      enabled_categories: [ ]
      disabled_categories: [ ]
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    ast-grep:
      packages: [ ]
      rule_dirs: [ ]
      util_dirs: [ ]
      essential_rules: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: [ ]
  linear:
    team_keys: [ ]
  pull_requests:
    scope: auto